const examples = {
  catch: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תחליף אותי לכלב', en: 'change the player to dog' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'ניקוד של 30', en: 'set target score to 30' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'תוסיף מטבעות', en: 'add coins' },
    { he: 'תחליף אותי לצפרדע', en: 'change the player to frog' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'תחליף אותי לרובוט', en: 'change the player to robot' },
    { he: 'רקע של ים', en: 'make the background ocean' },
  ],
  dodge: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תן לי 7 חיים', en: 'give me 7 lives' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תחליף אותי לחייזר', en: 'change the player to alien' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 15', en: 'set target score to 15' },
    { he: 'רקע של מדבר', en: 'make the background desert' },
    { he: 'תחליף אותי לציפור', en: 'change the player to bird' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'תחליף אותי לגיבור', en: 'change the player to hero' },
  ],
  jumper: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'תחליף אותי לארנב', en: 'change the player to bunny' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'תוסיף מטבעות', en: 'add coins' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תחליף אותי לחתול', en: 'change the player to cat' },
    { he: 'ניקוד של 20', en: 'set target score to 20' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'תחליף אותי לקוף', en: 'change the player to monkey' },
    { he: 'רקע של שמיים', en: 'make the background sky' },
  ],
  shooter: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 8 חיים', en: 'give me 8 lives' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תחליף אותי לרובוט', en: 'change the player to robot' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'ניקוד של 40', en: 'set target score to 40' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'תחליף אותי לחללית', en: 'change the player to spaceship' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'תחליף אותי לגיבור', en: 'change the player to hero' },
    { he: 'ניקוד של 100', en: 'set target score to 100' },
  ],
  pong: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 10', en: 'set target score to 10' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תן לי 7 חיים', en: 'give me 7 lives' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'רקע של ים', en: 'make the background ocean' },
    { he: 'ניקוד של 20', en: 'set target score to 20' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של מדבר', en: 'make the background desert' },
    { he: 'ניקוד של 5', en: 'set target score to 5' },
  ],
  breakout: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'רקע של ים', en: 'make the background ocean' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'ניקוד של 30', en: 'set target score to 30' },
    { he: 'רקע של שמיים', en: 'make the background sky' },
    { he: 'ניקוד של 100', en: 'set target score to 100' },
  ],
  snake: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 15', en: 'set target score to 15' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'ניקוד של 30', en: 'set target score to 30' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'רקע של מדבר', en: 'make the background desert' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
  ],
  memory: [
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'ניקוד של 10', en: 'set target score to 10' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של ים', en: 'make the background ocean' },
    { he: 'ניקוד של 20', en: 'set target score to 20' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'ניקוד של 5', en: 'set target score to 5' },
    { he: 'רקע של שמיים', en: 'make the background sky' },
    { he: 'רקע של מדבר', en: 'make the background desert' },
    { he: 'תן לי 7 חיים', en: 'give me 7 lives' },
    { he: 'ניקוד של 15', en: 'set target score to 15' },
  ],
  clicker: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'ניקוד של 25', en: 'set target score to 25' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תחליף אותי לחייזר', en: 'change the player to alien' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'תחליף אותי לרובוט', en: 'change the player to robot' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
  ],
  racer: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'תחליף אותי למכונית', en: 'change the player to car' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 30', en: 'set target score to 30' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'רקע של מדבר', en: 'make the background desert' },
    { he: 'תוסיף מטבעות', en: 'add coins' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
  ],
  flappy: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'תחליף אותי לציפור', en: 'change the player to bird' },
    { he: 'רקע של שמיים', en: 'make the background sky' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 20', en: 'set target score to 20' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תוסיף כוכבים', en: 'add stars' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'תחליף אותי לחללית', en: 'change the player to spaceship' },
    { he: 'ניקוד של 10', en: 'set target score to 10' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
  ],
  whack: [
    { he: 'תעשה אותי מהר יותר', en: 'make the player faster' },
    { he: 'יותר קשה', en: 'make it harder' },
    { he: 'תן לי 5 חיים', en: 'give me 5 lives' },
    { he: 'תעשה אותי גדול', en: 'make the player bigger' },
    { he: 'יותר קל', en: 'make it easier' },
    { he: 'תעשה אותי לאט יותר', en: 'make the player slower' },
    { he: 'ניקוד של 15', en: 'set target score to 15' },
    { he: 'רקע של דשא', en: 'make the background grass' },
    { he: 'תעשה אותי קטן', en: 'make the player smaller' },
    { he: 'רקע של יער', en: 'make the background forest' },
    { he: 'עוד חיים', en: 'add a life' },
    { he: 'תן לי 3 חיים', en: 'give me 3 lives' },
    { he: 'רקע של חלל', en: 'make the background space' },
    { he: 'תוסיף פצצות', en: 'add bombs' },
    { he: 'תוריד את הפצצות', en: 'remove bombs' },
    { he: 'ניקוד של 30', en: 'set target score to 30' },
    { he: 'רקע של לילה', en: 'make the background night' },
    { he: 'תן לי 10 חיים', en: 'give me 10 lives' },
    { he: 'רקע של עיר', en: 'make the background city' },
    { he: 'ניקוד של 50', en: 'set target score to 50' },
  ],
}

export function getExamples(templateId) {
  return examples[templateId] || []
}
